env:
  node: true
  jest: true

plugins:
  - babel
  - jest
  - import

parser: babel-eslint

extends: 
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  max-len: ["error", 100]